# Generated by Django 5.1.4 on 2025-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
