# Generated by Django 5.1.6 on 2025-03-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_securefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='aes_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='blowfish_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='des3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
