# Generated by Django 5.1.6 on 2025-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
